[versions]
jackson = "2.20.1"

[libraries]
archunit = "com.tngtech.archunit:archunit:1.4.1"
assertj = "org.assertj:assertj-core:3.27.6"
commons-collections = "org.apache.commons:commons-collections4:4.5.0"
commons-lang3 = "org.apache.commons:commons-lang3:3.20.0"
findbugs = "com.google.code.findbugs:jsr305:3.0.2"
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jdave = "club.minnced:jdave-api:0.1.0-rc.2"
jetbrains-annotations = "org.jetbrains:annotations:26.0.2-1"
junit = "org.junit.jupiter:junit-jupiter:6.0.1"
# @pin Newer versions require java 17 or higher
junit-java8 = "org.junit.jupiter:junit-jupiter:5.14.0"
junit-launcher = "org.junit.platform:junit-platform-launcher:6.0.1"
# @pin Newer versions require java 17 or higher
junit-launcher-java8 = "org.junit.platform:junit-platform-launcher:1.14.0"
logback-classic = "ch.qos.logback:logback-classic:1.5.23"
mockito = "org.mockito:mockito-core:5.21.0"
okhttp = "com.squareup.okhttp3:okhttp-jvm:5.3.2"
openrewrite-bom = "org.openrewrite.recipe:rewrite-recipe-bom:3.21.0"
reflections = "org.reflections:reflections:0.10.2"
slf4j = "org.slf4j:slf4j-api:2.0.17"
# @pin Newer versions require java 11 or higher
tink = "com.google.crypto.tink:tink:1.18.0"
trove4j = "net.sf.trove4j:core:3.1.0"
websocket-client = "com.neovisionaries:nv-websocket-client:2.14"

[bundles]
jackson = [
    "jackson-core",
    "jackson-databind",
]
junit = [
    "junit",
    "junit-launcher",
]
junit-java8 = [
    "junit-java8",
    "junit-launcher-java8",
]

[plugins]
ideax = "org.jetbrains.gradle.plugin.idea-ext:1.3"
jreleaser = "org.jreleaser:1.22.0"
openrewrite = "org.openrewrite.rewrite:7.23.0"
shadow = "com.gradleup.shadow:9.3.0"
# @pin Version 8.0.0 is incompatible with jreleaser (see https://github.com/jreleaser/jreleaser/issues/1989)
spotless = "com.diffplug.spotless:7.2.1"
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
versions = "com.github.ben-manes.versions:0.53.0"
